apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nutrition-analyzer-ingress
  namespace: "2401178-nutritionanalyzer"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nutrition-2401178.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nutrition-analyzer-service
                port:
                  number: 8000
