apiVersion: v1
kind: Service
metadata:
  name: nutrition-analyzer-service
  namespace: "2401178-nutritionanalyzer"
spec:
  selector:
    app: nutrition-analyzer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
